name: App Lint / Test / Build
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: App Install dependencies
        working-directory: ./apps/build-onchain-apps
        run: npm install
      - name: App Lint Check
        working-directory: ./apps/build-onchain-apps
        # When fails, please run "npm run lint" to your code
        run: npm run lint
      - name: Add Stylelint
        working-directory: ./apps/build-onchain-apps
        run: npm run stylelint
      - name: App Test Check
        working-directory: ./apps/build-onchain-apps
        # When fails, please check your tests
        run: npm run test
      - name: App Test Build
        working-directory: ./apps/build-onchain-apps
        # When fails, please check your build
        run: | 
          cp .env.local.default .env.local
          npm run build
